### ISSUE TITLE
Stories can't be created if project id is given in argument

### ISSUE THREAD

**Issue by ohe** [shortcut-cli/shortcut-cli#293]
It must be possible to create a story by using the project id via `story create`

Example:

```story create --project 123 --title "Test" -d "Desc"```

will always return 

```Must provide --title and --project```

After a short investigation, it appears that in the method `fetchEntities`, the code part 

```
                        client_1.default
                            .listProjects()
                            .then(function (r) { return r.data; })
                            .then(mapByItemId),
```

returns a map of int -> Object when the project id is passed to the cli as string.

A very naive attempt to fix this issue would be, in `findEntity` method to try to fetch the entity as a string then as an int (as some entity can be strings) before trying to regex on name attribute.

Last but not least, the PR https://github.com/shortcut-cli/shortcut-cli/pull/292 was trying to solve epic association with created stories. If one is giving the epic Id, the same issue will be also observed.

**Comment by j-martin** [comment]
Fixed in `3.2.1`.
